In [7]:


#Importing all necessary libraries for data wrangling and visualisation
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
# sklearn preprocessing tools
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid", context="notebook")
plt.rcParams.update({
    "figure.dpi": 110,
    "axes.titlesize": 14,
    "axes.titleweight": "bold",
    "axes.labelsize": 11,
    "font.size": 10,
    "axes.edgecolor": "#4d4d4d",
    "grid.alpha": 0.3,
})

In [8]:
# Read the raw file as plain text first, bypass pandas entirely for this step
with open("jobs_in_data.csv", "r", encoding="utf-8-sig") as f:
    raw_text = f.read()

# Remove every literal quote character -- none of this dataset's actual values
# need quoting (no field contains a semicolon or comma inside it), so this is safe

In [9]:
df.head()

  work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0  2023,Data DevOps Engineer,Data Engineering,EUR...
1  2023,Data Architect,Data Architecture and Mode...
2  2023,Data Architect,Data Architecture and Mode...
3  2023,Data Scientist,Data Science and Research,...
4  2023,Data Scientist,Data Science and Research,...

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9355 entries, 0 to 9354
Data columns (total 1 columns):
 #   Column                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                --------------  -----
 0   work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size  9355 non-null   str
dtypes: str(1)
memory usage: 1.1 MB

In [ ]:
df.shape

(9355, 1)

In [15]:
# ─────────────────────────────────────────────────
# VISUALIZATION 1: SALARY DISTRIBUTION
# ─────────────────────────────────────────────────

plt.figure(figsize=(12, 5))
sns.histplot(df['salary'], bins=60, kde=True, color='steelblue')
plt.title('Distribution of Data Professional Salaries (USD)', fontsize=14, fontweight='bold')
plt.xlabel('Salary in USD')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

KeyError: 'salary'

In [16]:
categorical_cols = df.select_dtypes(include=['object']).columns
jobs_data_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("Original data shape:", df.shape)
print("Encoded data shape:", jobs_data_encoded.shape)
print("First 5 rows of encoded data:")
jobs_data_encoded.head()

Original data shape: (9355, 1)
Encoded data shape: (9355, 5340)
First 5 rows of encoded data:

,"work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Azure Data Engineer,Data Engineering,USD,100000,100000,Mauritius,Entry-level,Full-time,In-person,Mauritius,S","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,BI Data Analyst,Data Analysis,USD,98000,98000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Big Data Engineer,Data Engineering,EUR,100000,114047,Poland,Senior,Full-time,Remote,United Kingdom,S","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Big Data Engineer,Data Engineering,GBP,85000,109024,United Kingdom,Senior,Full-time,Hybrid,United Kingdom,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Big Data Engineer,Data Engineering,USD,70000,70000,United States,Entry-level,Full-time,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Business Data Analyst,Data Analysis,USD,100000,100000,United States,Entry-level,Contract,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Business Data Analyst,Data Analysis,USD,135000,135000,United States,Mid-level,Full-time,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Business Data Analyst,Data Analysis,USD,95000,95000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Computer Vision Engineer,Machine Learning and AI,USD,60000,60000,Russia,Senior,Freelance,Remote,United States,S","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Data Analyst,Data Analysis,EUR,20000,22809,Portugal,Entry-level,Full-time,Remote,Portugal,M",...,"work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,70000,70000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,76000,76000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,85000,85000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,90600,90600,United States,Senior,Full-time,Remote,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,90700,90700,United States,Senior,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,94192,94192,United States,Senior,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Software Data Engineer,Data Engineering,SGD,100000,74883,Singapore,Mid-level,Full-time,Remote,Singapore,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Software Data Engineer,Data Engineering,USD,210000,210000,United States,Senior,Full-time,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Software Data Engineer,Data Engineering,USD,50000,50000,Nigeria,Senior,Freelance,Hybrid,Australia,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Staff Data Analyst,Data Analysis,USD,179998,179998,Saudi Arabia,Mid-level,Full-time,Remote,Saudi Arabia,S"
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
display(jobs_data_encoded.head())

,"work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Azure Data Engineer,Data Engineering,USD,100000,100000,Mauritius,Entry-level,Full-time,In-person,Mauritius,S","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,BI Data Analyst,Data Analysis,USD,98000,98000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Big Data Engineer,Data Engineering,EUR,100000,114047,Poland,Senior,Full-time,Remote,United Kingdom,S","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Big Data Engineer,Data Engineering,GBP,85000,109024,United Kingdom,Senior,Full-time,Hybrid,United Kingdom,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Big Data Engineer,Data Engineering,USD,70000,70000,United States,Entry-level,Full-time,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Business Data Analyst,Data Analysis,USD,100000,100000,United States,Entry-level,Contract,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Business Data Analyst,Data Analysis,USD,135000,135000,United States,Mid-level,Full-time,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Business Data Analyst,Data Analysis,USD,95000,95000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Computer Vision Engineer,Machine Learning and AI,USD,60000,60000,Russia,Senior,Freelance,Remote,United States,S","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2020,Data Analyst,Data Analysis,EUR,20000,22809,Portugal,Entry-level,Full-time,Remote,Portugal,M",...,"work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,70000,70000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,76000,76000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,85000,85000,United States,Mid-level,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,90600,90600,United States,Senior,Full-time,Remote,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,90700,90700,United States,Senior,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Research Scientist,Data Science and Research,USD,94192,94192,United States,Senior,Full-time,In-person,United States,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Software Data Engineer,Data Engineering,SGD,100000,74883,Singapore,Mid-level,Full-time,Remote,Singapore,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Software Data Engineer,Data Engineering,USD,210000,210000,United States,Senior,Full-time,Remote,United States,L","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Software Data Engineer,Data Engineering,USD,50000,50000,Nigeria,Senior,Freelance,Hybrid,Australia,M","work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size_2023,Staff Data Analyst,Data Analysis,USD,179998,179998,Saudi Arabia,Mid-level,Full-time,Remote,Saudi Arabia,S"
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
# ─────────────────────────────────────────────────
# VISUALIZATION 2: AVERAGE SALARY BY EXPERIENCE LEVEL
# ─────────────────────────────────────────────────

plt.figure(figsize=(10, 5))
exp_salary = df.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=False)
sns.barplot(x=exp_salary.index, y=exp_salary.values, palette='Blues_d')
plt.title('Average Salary by Experience Level', fontsize=14, fontweight='bold')
plt.xlabel('Experience Level')
plt.ylabel('Average Salary (USD)')
plt.tight_layout()
plt.show()

KeyError: 'experience_level'

In [19]:
# Define features (X) by dropping the original salary columns and the target variable
X = jobs_data_encoded.drop(['salary_in_usd', 'salary'] + [col for col in jobs_data_encoded.columns if 'salary_currency_' in col], axis=1)

# Define the target (y) as 'salary_in_usd' for regression
y = jobs_data_encoded['salary_in_usd']

print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

print("\nFirst 5 rows of features (X):")
display(X.head())

print("\nFirst 5 rows of target (y):")
display(y.head())

KeyError: "['salary_in_usd', 'salary'] not found in axis"

In [20]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

NameError: name 'X' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize the Linear Regression model
linear_model = LinearRegression()

# Training the model
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_linear = linear_model.predict(X_test)

# Evaluate the model
mae_linear = mean_absolute_error(y_test, y_pred_linear)
mse_linear = mean_squared_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mse_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print("Linear Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_linear:.2f}")
print(f"Mean Squared Error (MSE): {mse_linear:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_linear:.2f}")
print(f"R-squared (R2): {r2_linear:.2f}")

In [21]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("### Hyperparameter Tuning for Ridge Regression ###")

# Define the parameter grid for Ridge Regression
param_grid_ridge = {'alpha': np.logspace(-4, 2, 7)}

# Initialize GridSearchCV for Ridge
grid_search_ridge = GridSearchCV(Ridge(), param_grid_ridge, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search_ridge.fit(X_train, y_train)

# Get the best Ridge model
best_ridge_model = grid_search_ridge.best_estimator_

print(f"Best parameters for Ridge: {grid_search_ridge.best_params_}")
print(f"Best cross-validation MSE for Ridge: {-grid_search_ridge.best_score_:.2f}")

# Make predictions with the best Ridge model
y_pred_ridge = best_ridge_model.predict(X_test)

# Evaluate the best Ridge model
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("\nBest Ridge Model Performance on Test Set:")
print(f"Mean Absolute Error (MAE): {mae_ridge:.2f}")
print(f"Mean Squared Error (MSE): {mse_ridge:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_ridge:.2f}")
print(f"R-squared (R2): {r2_ridge:.2f}")

print("\n### Hyperparameter Tuning for Lasso Regression ###")

# Define the parameter grid for Lasso Regression
param_grid_lasso = {'alpha': np.logspace(-4, 2, 7)}

# Initialize GridSearchCV for Lasso
grid_search_lasso = GridSearchCV(Lasso(max_iter=2000), param_grid_lasso, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search_lasso.fit(X_train, y_train)

# Get the best Lasso model
best_lasso_model = grid_search_lasso.best_estimator_

print(f"Best parameters for Lasso: {grid_search_lasso.best_params_}")
print(f"Best cross-validation MSE for Lasso: {-grid_search_lasso.best_score_:.2f}")

# Make predictions with the best Lasso model
y_pred_lasso = best_lasso_model.predict(X_test)

# Evaluate the best Lasso model
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("\nBest Lasso Model Performance on Test Set:")
print(f"Mean Absolute Error (MAE): {mae_lasso:.2f}")
print(f"Mean Squared Error (MSE): {mse_lasso:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_lasso:.2f}")
print(f"R-squared (R2): {r2_lasso:.2f}")

### Hyperparameter Tuning for Ridge Regression ###

NameError: name 'X_train' is not defined

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Initialize the KNN Regressor model
# A common starting point for n_neighbors is 5, but this is a hyperparameter to tune.
knn_model = KNeighborsRegressor(n_neighbors=5)

# Train the model
knn_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print("K-Nearest Neighbors (KNN) Regressor Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"R-squared (R2): {r2_knn:.2f}")

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("### Hyperparameter Tuning for K-Nearest Neighbors Regressor ###")

# Define the parameter grid for n_neighbors
param_grid_knn = {'n_neighbors': range(1, 21)} # Test k from 1 to 20

# Initialize GridSearchCV for KNN
grid_search_knn = GridSearchCV(KNeighborsRegressor(), param_grid_knn, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search_knn.fit(X_train, y_train)

# Get the best KNN model
best_knn_model = grid_search_knn.best_estimator_

print(f"Best parameters for KNN: {grid_search_knn.best_params_}")
print(f"Best cross-validation MSE for KNN: {-grid_search_knn.best_score_:.2f}")

# Make predictions with the best KNN model
y_pred_best_knn = best_knn_model.predict(X_test)

# Evaluate the best KNN model
mae_best_knn = mean_absolute_error(y_test, y_pred_best_knn)
mse_best_knn = mean_squared_error(y_test, y_pred_best_knn)
rmse_best_knn = np.sqrt(mse_best_knn)
r2_best_knn = r2_score(y_test, y_pred_best_knn)

print("\nBest KNN Model Performance on Test Set:")
print(f"Mean Absolute Error (MAE): {mae_best_knn:.2f}")
print(f"Mean Squared Error (MSE): {mse_best_knn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_best_knn:.2f}")
print(f"R-squared (R2): {r2_best_knn:.2f}")

In [ ]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("### Applying Stack Ensemble Regressor ###")

# Define base estimators using the best models from previous steps
# Using best_ridge_model and best_knn_model as found during hyperparameter tuning
estimators = [
    ('ridge', best_ridge_model),
    ('knn', best_knn_model)
]

# Define the meta-estimator (final regressor)
final_estimator = LinearRegression()

# Initialize the Stacking Regressor
stack_model = StackingRegressor(
    estimators=estimators,
    final_estimator=final_estimator,
    cv=5, # Number of cross-validation folds for stacking
    n_jobs=-1 # Use all available cores
)

# Train the Stacking Regressor
stack_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_stack = stack_model.predict(X_test)

# Evaluate the stacked model
mae_stack = mean_absolute_error(y_test, y_pred_stack)
mse_stack = mean_squared_error(y_test, y_pred_stack)
rmse_stack = np.sqrt(mse_stack)
r2_stack = r2_score(y_test, y_pred_stack)

print("\nStack Ensemble Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_stack:.2f}")
print(f"Mean Squared Error (MSE): {mse_stack:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_stack:.2f}")
print(f"R-squared (R2): {r2_stack:.2f}")